name: Build
on: [push, pull_request]
jobs:
  test:
    name: "Build on Node.js ${{ matrix.node-version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 17
          - 18
          - 19
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: check
        run: ls -al ./lib
